CREATE PROC FI_SP_IncBeneficiarioV2    
    @CPF           VARCHAR (15) ,
    @NOME          VARCHAR (255),
    @IDCLIENTE     BIGINT    
AS
BEGIN
	INSERT INTO BENEFICIARIOS (CPF, NOME, IDCLIENTE) 
	VALUES (@CPF, @NOME, @IDCLIENTE)

	SELECT SCOPE_IDENTITY()
END